# Generated by Django 5.1 on 2024-09-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_remove_post_content_remove_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="BldgType",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="BsmtCond",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="BsmtQual",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="CentralAir",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="ExterCond",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="ExterQual",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="FirstFlrSF",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="Foundation",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="GarageArea",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="GarageCars",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="GarageCond",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="GarageQual",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="GarageType",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="GrLivArea",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="KitchenQual",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="LotArea",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="LotFrontage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="MSZoning",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="MiscVal",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="OverallCond",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="OverallQual",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="PoolArea",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="RoofMatl",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="RoofStyle",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="SaleConditionRoofStyle",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="SaleType",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="SecondFlrSF",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="TotRmsAbvGrd",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="TotalBsmtSF",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="YearBuilt",
            field=models.IntegerField(default=0),
        ),
    ]
