# Generated by Django 5.1 on 2024-09-13 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_bldgtype_post_bsmtcond_post_bsmtqual_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="SaleConditionRoofStyle",
            new_name="SaleCondition",
        ),
    ]
