# Generated by Django 5.1 on 2024-09-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_rename_saleconditionroofstyle_post_salecondition"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Exterior1st",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="Exterior2nd",
            field=models.CharField(default="", max_length=50),
        ),
    ]
