# Generated by Django 5.1.1 on 2024-09-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_post_post_pic1_post_post_pic2_post_post_pic3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
