# Generated by Django 5.1.1 on 2024-09-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_post_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
    ]
