# Generated by Django 5.1.1 on 2024-09-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_post_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="map",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AddField(
            model_name="post",
            name="use_for",
            field=models.IntegerField(default=0),
        ),
    ]
