# Generated by Django 5.1.1 on 2024-10-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
