# Generated by Django 5.1.1 on 2024-10-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_review_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_pic1",
            field=models.ImageField(default="empty.jpg", upload_to="post_pic1"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_pic2",
            field=models.ImageField(default="empty.jpg", upload_to="post_pic2"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_pic3",
            field=models.ImageField(default="empty.jpg", upload_to="post_pic3"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_pic4",
            field=models.ImageField(default="empty.jpg", upload_to="post_pic4"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_pic5",
            field=models.ImageField(default="empty.jpg", upload_to="post_pic5"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_pic6",
            field=models.ImageField(default="empty.jpg", upload_to="post_pic6"),
        ),
    ]
