# Generated by Django 5.1.1 on 2024-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="experience_year",
            field=models.IntegerField(default=0),
        ),
    ]
