# Generated by Django 5.1.1 on 2024-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="applicant",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="applicant",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="applicant",
            name="email",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="applicant",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="applicant",
            name="full_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="applicant",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="applicant",
            name="zipcode",
            field=models.IntegerField(default=0),
        ),
    ]
