# Generated by Django 5.1.1 on 2024-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_applicant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
