# Generated by Django 5.1.1 on 2024-11-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="has_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="project_city",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="project",
            name="project_country",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="project",
            name="project_zip",
            field=models.IntegerField(default=0),
        ),
    ]
