# Generated by Django 5.1.1 on 2024-11-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manage", "0002_project_has_closed_project_project_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="has_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="project_description",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="project",
            name="project_proposal_doc",
            field=models.FileField(default=None, upload_to="project_proposal_docs/"),
        ),
    ]
