# Generated by Django 5.1.1 on 2024-11-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manage", "0006_alter_project_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_location",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_proposal_doc",
            field=models.FileField(
                default=None, null=True, upload_to="project_proposal_docs/"
            ),
        ),
    ]
