# Generated by Django 5.1.1 on 2024-11-11 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_manage", "0007_alter_project_project_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_proposal_doc",
        ),
    ]
