# Generated by Django 5.1.1 on 2024-11-11 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manage", "0008_remove_project_project_proposal_doc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_payment", models.IntegerField(default=0)),
                ("labor_wages_payment", models.IntegerField(default=0)),
                ("other_wages_payment", models.IntegerField(default=0)),
                ("salary_payment", models.IntegerField(default=0)),
                ("transport_payment", models.IntegerField(default=0)),
                ("revenue", models.IntegerField(default=0)),
                ("no_of_installment", models.IntegerField(default=1)),
                ("installment_payment", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manage.project",
                    ),
                ),
            ],
        ),
    ]
