# Generated by Django 5.1.1 on 2024-11-11 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manage", "0009_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_title", models.CharField(default="", max_length=50)),
                ("purchase_amount", models.IntegerField(default=0)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manage.payment",
                    ),
                ),
            ],
        ),
    ]
