# Generated by Django 5.1.1 on 2024-11-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manage", "0010_purchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborWagePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("labor_wage_title", models.CharField(default="", max_length=50)),
                ("labor_wage_amount", models.IntegerField(default=0)),
                (
                    "labor_wage_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manage.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherWagePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("other_wage_title", models.CharField(default="", max_length=50)),
                ("other_wage_amount", models.IntegerField(default=0)),
                (
                    "other_wage_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manage.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary_title", models.CharField(default="", max_length=50)),
                ("salary_amount", models.IntegerField(default=0)),
                (
                    "salary_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manage.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transport_title", models.CharField(default="", max_length=50)),
                ("transport_amount", models.IntegerField(default=0)),
                (
                    "transport_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manage.payment",
                    ),
                ),
            ],
        ),
    ]
